### ISSUE TITLE
kotlinx-benchmark 0.4.6 cannot find custom compilations of Kotlin 1.8.0

### ISSUE THREAD

**Issue by lounres** [Kotlin/kotlinx-benchmark#103]
> MRE: https://github.com/lounres/kotlinx-benchmark-103/tree/89892cfb5198f811d1aa7eeb0704e74026288d67

I have a multimodule multiplatform project with kotlinx-benchmark 0.4.6 and Kotlin 1.7.21. In all multiplatform modules for each target I add a special compilation for benchmarks and register such JVM compilation in kotlinx-benchmark. It worked well. But after I upgraded Kotlin to version 1.8.0 kotlinx-benchmark Gradle plugin cannot find the compilation any more. It logs
```
Warning: Cannot find a benchmark compilation 'jvmBenchmarks', ignoring.
```

To reproduce the problem, open the MRE and just change version `kotlin` in `gradle/libs.versions.toml` to `"1.8.0"`.

**Comment by qurbonzoda** [comment]
The problem with the project configuration is in this line: https://github.com/lounres/kotlinx-benchmark-103/blob/89892cfb5198f811d1aa7eeb0704e74026288d67/build.gradle.kts#L68

Please change `benchmarks.defaultSourceSetName` to `"jvm"` (or `it.platformType.name`) and upgrade to kotlinx-benchmark 0.4.7. The latest version should work with kotlin 1.8.0.

I suppose the breaking change was introduced within [this issue](https://youtrack.jetbrains.com/issue/KT-35916), where compilation configuration names were changed.

Note that you can use a Java sourceSet name as a target only in non-multiplatform (jvm-only) projects.

**Comment by lounres** [comment]
Yeah, kotlinx-benchmark 0.4.7 and Kotlin 1.8.0 with `platformType.name` works well.

But I really want to separate main source set from benchmark source set but also have them in the same module. Is it possible in multiplatform project?

**Comment by lounres** [comment]
Made a workaround:
```kotlin
import kotlinx.benchmark.gradle.BenchmarksExtension
import kotlinx.benchmark.gradle.KotlinJvmBenchmarkTarget

...

// The kotlinx-benchmark extension
val benchmarksExtension: BenchmarksExtension = the<BenchmarksExtension>()
// Kotlin compilation used for benchmarks
val benchmarks: KotlinJvmCompilation = ...
// Name of the compilation main source set
val benchmarksSourceSetName: String = benchmarks.defaultSourceSet.name

...

// Manually create Kotlin/JVM Benchmark target for the compilation and add it to targets container
val benchmarkTarget = KotlinJvmBenchmarkTarget(
    extension = benchmarksExtension,
    name = benchmarksSourceSetName,
    compilation = benchmarks
)
benchmarksExtension.targets.add(benchmarkTarget)
```

Now everything works well. But it will be cool if it can be done by means of the plugin.

**Comment by Quillraven** [comment]
Hi, I think I have a similar issue. Can someone please guide me into the right direction? When I upgrade to Kotlin 1.8 with kotlinx.benchmark 0.4.5 I suddenly get an error that `openjdk.jmh` is an unresolved reference and therefore the annotations do no longer work.

Is it possible to write benchmarks without the annotations? Here is an example how I wrote my benchmarks so far:

```kotlin
@State(Scope.Benchmark)
open class FleksStateComplex {
    lateinit var world: World

    @Setup(value = Level.Iteration)
    fun setup() {
        world = world(NUM_ENTITIES) {
            systems {
                add(FleksSystemComplex1())
                add(FleksSystemComplex2())
            }
        }

        repeat(NUM_ENTITIES) {
            world.entity {
                it += FleksPosition()
                it += FleksSprite()
            }
        }
    }
}

@Fork(value = WARMUPS)
@Warmup(iterations = WARMUPS)
@Measurement(iterations = ITERATIONS, time = TIME, timeUnit = TimeUnit.SECONDS)
open class FleksBenchmark {
    @Benchmark
    fun addRemove(state: FleksStateAddRemove) {
        repeat(NUM_ENTITIES) {
            state.world.entity {
                it += FleksPosition()
            }
        }
        repeat(NUM_ENTITIES) {
            state.world -= Entity(it)
        }
    }

    @Benchmark
    fun simple(state: FleksStateSimple) {
        repeat(WORLD_UPDATES) {
            state.world.update(1f)
        }
    }

    @Benchmark
    fun complex(state: FleksStateComplex) {
        repeat(WORLD_UPDATES) {
            state.world.update(1f)
        }
    }
}
```

If that is not possible then I guess I need to adjust something in my gradle file to work again? I tried version 0.4.7 but it doesn`t solve my issue. The important gradle part looks like this:

```kotlin
kotlin {
    targets {
        jvm {
            compilations {
                all {
                    kotlinOptions {
                        jvmTarget = "1.8"
                    }
                }
                val main by getting { }
                // custom benchmark compilation
                val benchmarks by compilations.creating {
                    defaultSourceSet {
                        dependencies {
                            // Compile against the main compilation's compile classpath and outputs:
                            implementation(main.compileDependencyFiles + main.output.classesDirs)
                        }
                    }
                }
            }
            withJava()
            testRuns["test"].executionTask.configure {
                useJUnitPlatform()
            }
        }
    }
    js(BOTH) {
        browser { }
    }
    val hostOs = System.getProperty("os.name")
    val isMingwX64 = hostOs.startsWith("Windows")
    val nativeTarget = when {
        hostOs == "Mac OS X" -> macosX64("native")
        hostOs == "Linux" -> linuxX64("native")
        isMingwX64 -> mingwX64("native")
        else -> throw GradleException("Host OS is not supported in Kotlin/Native.")
    }

    sourceSets {
        val commonMain by getting { }
        val commonTest by getting {
            dependencies {
                implementation(kotlin("test"))
            }
        }
        val jvmMain by getting
        val jvmTest by getting
        val jvmBenchmarks by getting {
            dependsOn(commonMain)
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-benchmark-runtime:0.4.5")
                implementation("com.badlogicgames.ashley:ashley:1.7.4")
                implementation("net.onedaybeard.artemis:artemis-odb:2.3.0")
            }
        }
        val jsMain by getting
        val jsTest by getting
        val nativeMain by getting
        val nativeTest by getting
    }
}

benchmark {
    targets {
        register("jvmBenchmarks")
    }
}
```

With that setup I am able to have a separate benchmark sourceset and gradle task in my multiplatform environment:
![image](https://user-images.githubusercontent.com/93260/220772191-e8024ab9-c8a9-431e-83cd-fe992a4ba7ac.png)

In my case I was not able to replace defaultSourceSet with "jvm" or platformType.name. I then get an error that there is no jvm sourceset.

I tried a few other variations. Some synced correctly, like my current setup, but the jmh unresolved reference remained. Other variations cause gradle to end up in a StackOverflow error.

Since I am no gradle expert, I'd appreciate some help to let me know how to fix it. Or will there be a new version soon that fixes this error and I don`t need to adjust my gradle file?

Thanks for any help!
