### ISSUE TITLE
Running jvm benchmarks requires dependency not listed in readme

### ISSUE THREAD

**Issue by Munzey** [Kotlin/kotlinx-benchmark#16]
Dug around on https://dl.bintray.com/kotlin/kotlinx and found I needed `"org.jetbrains.kotlinx:kotlinx.benchmark.runtime-jvm:0.2.0-dev-7"` to get it to work.

**Comment by qurbonzoda** [comment]
Updated README now clarifies platform artifact dependecy.
Thanks for the feedback!
