### ISSUE TITLE
Native benchmark fails on 0.4.9

### ISSUE THREAD

**Issue by CharlieTap** [Kotlin/kotlinx-benchmark#162]
I'm running:

Kotlin 1.9.2
OS: Sonoma
CPU: Apple M1 Max
Gradle: 8.4

You can recreate by running build on this branch:

https://github.com/CharlieTap/cachemap/tree/failing-benchmark

I get the following:

Execution failed for task ':benchmark:macosArm64BenchmarkGenerate'.
> There was a failure while executing work items
   > A failure occurred while executing kotlinx.benchmark.gradle.NativeSourceGeneratorWorker
      > e: Could not find "/cachemap/benchmark/build/classes/kotlin/macosArm64/main/klib/benchmark.klib" in [cachemap]

**Comment by qurbonzoda** [comment]
Hi,
We are currently in the process of supporting Kotlin 1.9.20.
Thanks for your feedback!

**Comment by qurbonzoda** [comment]
Kotlin 1.9.20/21 is supported in the latest release 0.4.10. Please check it out and share your feedback.
