### ISSUE TITLE
Include useful allOpen annotation example in readme

### ISSUE THREAD

**Issue by Munzey** [Kotlin/kotlinx-benchmark#17]
it would make more sense to explain that if for example you annotated each of your benchmark classes with 
```kt
@BenchmarkMode(Mode.Throughput)
class Benchmark {}
```
and added to your build.gradle:
```groovy
allOpen {
    annotation("org.openjdk.jmh.annotations.BenchmarkMode")
}
```
then you dont need to make things open. I think this would make it easier to follow

**Comment by qurbonzoda** [comment]
Updates README now provides the example.
Thanks for your feedback!
