### ISSUE TITLE
Missing Kotlin Multiplatform Kts example

### ISSUE THREAD

**Issue by MohamedRejeb** [Kotlin/kotlinx-benchmark#218]
Hi,
In the examples there's a kts example but only for Kotlin/JVM, it will be helpful if you can provide an example with Kotlin Multiplatform and kts.

**Comment by qurbonzoda** [comment]
Hi,

Thanks for the feedback. Indeed, the sample projects are outdated and could benefit from using Kotlin DSL (.kts). [Here](https://github.com/Kotlin/kotlinx-benchmark/issues/183), we have a dedicated issue to track the task. Please add to the comments what samples would be helpful to you.
