### ISSUE TITLE
Error with compiling build.gradle.kts

### ISSUE THREAD

**Issue by foiki** [Kotlin/kotlinx-benchmark#23]
Updated settings.gradle, added plugin import, dependencies and implementations but this error still being issued during compilation
---
A problem occurred configuring root project 'projectName'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find org.jetbrains.kotlin:kotlin-native-library-reader:1.3.40-eap-105.
     Searched in the following locations:
       - https://dl.bintray.com/kotlin/kotlinx/org/jetbrains/kotlin/kotlin-native-library-reader/1.3.40-eap-105/kotlin-native-library-reader-1.3.40-eap-105.pom
       - https://plugins.gradle.org/m2/org/jetbrains/kotlin/kotlin-native-library-reader/1.3.40-eap-105/kotlin-native-library-reader-1.3.40-eap-105.pom
     Required by:
         project : > kotlinx.benchmark:kotlinx.benchmark.gradle.plugin:0.2.0-dev-2 > org.jetbrains.kotlinx:kotlinx.benchmark.gradle:0.2.0-dev-2

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by qurbonzoda** [comment]
Now that the library does not depend on `kotlin-native-library-reader`, I close the issue.
Thanks for your feedback!
