### ISSUE TITLE
Native benchmarks runner doesn't allow to get right  measurements

### ISSUE THREAD

**Issue by LepilkinaElena** [Kotlin/kotlinx-benchmark#24]
Current implementation for K/N part cann't provide realistic results because some features of K/N runtime aren't taken into account.
Wrong performance results can confuse K/N users and let them make wrong conclusion.

**Comment by LepilkinaElena** [comment]
At least 
1) GC is called automatically, so garbage from one benchmark (and from runner) influences now on results of others.
2) There are several thresholds in K/N runtime that are changing during execution, they influence on performance. Each benchmark should be run separately.
3) There are some situations (with singletons) where even each run of one benchmark should be done as separate binary run.

**Comment by qurbonzoda** [comment]
https://github.com/Kotlin/kotlinx-benchmark/pull/32 resolves the concerns listed.
