### ISSUE TITLE
NO SOURCE for native targets, using Kotlin 2.1 (dev builds)

### ISSUE THREAD

**Issue by sellmair** [Kotlin/kotlinx-benchmark#259]
Using recent Kotlin 2.1 builds (e.g. 2.1.0-dev-6359)

```kotlin
plugins {
    kotlin("multiplatform")
    id("org.jetbrains.kotlinx.benchmark")
}

kotlin {
    jvm()
    macosArm64()

    sourceSets.commonMain.dependencies {
        implementation("org.jetbrains.kotlinx:kotlinx-benchmark-runtime:0.4.11")
    }
}

benchmark {
    targets {
        register("jvm")
        register("macosArm64")
    }
}
```

Then executing `macosArm64Benchmark` is skipped because of ' NO-SOURCE

## Reproducer Project: 
https://github.com/sellmair/kotlin-multiplatform-projects/tree/KT-70695/Float-Double.isFinite-can-be-optimized-kotlinx-report

**Comment by qurbonzoda** [comment]
This should be fixed in the latest version 0.4.13
