### ISSUE TITLE
Error: Incompatible Type: There may be a loss in converting from double to long

### ISSUE THREAD

**Issue by li-fcb1899** [Kotlin/kotlinx-benchmark#262]
BenchmarkTaskResult results = new BenchmarkTaskResult(res.allOps, res.measuredOps);
![image](https://github.com/user-attachments/assets/92cc7558-c26b-45ea-b876-6293d7c4527a)

In the generated Java code
```
RawResults res = new RawResults();
/*...*/
 BenchmarkTaskResult results = new BenchmarkTaskResult(res.allOps, res.measuredOps);
```
but
```
public class RawResults {

    public double allOps;
    public double measuredOps;
    /*...*/
}
```
```
public BenchmarkTaskResult(long allOperations, long measuredOperations)
```
Why treat double as long？

**Comment by fzhinkin** [comment]
Hey @li-fcb1899! Could you please share some details on how to reproduce the issue?
