### ISSUE TITLE
js benchmark task failing with kotlin version > 1.4.10

### ISSUE THREAD

**Issue by Munzey** [Kotlin/kotlinx-benchmark#28]
For any kotlin version higher than 1.4.10 I'm getting the following gradle error with js benchmarking target:

Execution failed for task ':benchmarks:jsBenchmarkGenerate'.
> Caused by: java.lang.NoSuchMethodError: kotlin.collections.CollectionsKt.maxOrNull(Ljava/lang/Iterable;)Ljava/lang/Comparable;
	at org.jetbrains.kotlin.serialization.deserialization.MemberDeserializer.computeExperimentalityModeForFunctions(MemberDeserializer.kt:233)

**Comment by qurbonzoda** [comment]
Please use the latest version 0.3.0 of this library with Kotlin 1.4.30.
Looking for your feedback.
