### ISSUE TITLE
Enhancement: custom output titles

### ISSUE THREAD

**Issue by teenriot** [Kotlin/kotlinx-benchmark#282]
Thanks for your work providing us this library.

A little enhancement i would like to have is the option to add custom titles to benchmarks for more concise output.
At the moment it looks like this:

```
Benchmark                     Mode  Cnt       Score      Error  Units
PlaygroundBenchmark.byIndex  thrpt   30  391996,917 ± 1618,767  ops/s
PlaygroundBenchmark.byRange  thrpt   30  392183,715 ±  592,562  ops/s
PlaygroundBenchmark.loop     thrpt   30  364886,733 ±  812,489  ops/s
```

i would like to have something like:
```
@Output(title = "Foo")
open class FooBenchmark {
    @Benchmark(title = "bar1")
    fun byIndex(blackhole: Blackhole) {
```
to produce:
```
Benchmark  Mode  Cnt       Score      Error  Units
Foo.bar1  thrpt   30  391996,917 ± 1618,767  ops/s
Foo.bar2  thrpt   30  392183,715 ±  592,562  ops/s
Foo.bar3  thrpt   30  364886,733 ±  812,489  ops/s
```

**Comment by fzhinkin** [comment]
@teenriot, could you please elaborate how would it differ from simply renaming benchmark methods?

**Comment by teenriot** [comment]
The title of methods and classes are technically names while the output is made for humans and therefor should use human readable titles. But for sure this is just cosmetic, don't improve functionality and has no priority.

**Comment by fzhinkin** [comment]
Fair enough

**Comment by teenriot** [comment]
I close this tickets. When i wrote it i wasn't aware that the JVM-part is build on top on JMH. When JMH don't support such options, nobody needs it and why should kotlinx do so? Also, in kotlin you are very free in naming methods by using backticks.
