### ISSUE TITLE
WorkerExecutor.submit is deprecated

### ISSUE THREAD

**Issue by ilya-g** [Kotlin/kotlinx-benchmark#48]
The method `WorkerExecutor.submit` used in `JmhBytecodeGeneratorTask` is deprecated in Gradle and will be removed in Gradle 8.  We need to migrate to using one of its work queues, for example to `noIsolation()`. 
`JmhBytecodeGeneratorWorker` also has to be migrated to implement `WorkAction<>` interface.

More details here: https://docs.gradle.org/current/userguide/upgrading_version_5.html#method_workerexecutor_submit_is_deprecated

**Comment by qurbonzoda** [comment]
Fixed.
