### ISSUE TITLE
Crash on Js Benchmark Dependencies Task

### ISSUE THREAD

**Issue by gabrielhuff** [Kotlin/kotlinx-benchmark#5]
I got a crash [here](https://github.com/orangy/gradle-benchmarks/blob/eff981eb8e0a439d7e6088d93c7dea2ffad0e7f0/plugin/main/src/org/jetbrains/gradle/benchmarks/JsNodeTasks.kt#L134) on `rootProject.project()`.

Apparently it happens when a project dependency has more than 1 subpath, e.g. `:path:to:foo`: in this case [`projectName`](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/component/ProjectComponentIdentifier.html#getProjectName--) looks to be returning only `foo`. Maybe [`projectPath`](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/component/ProjectComponentIdentifier.html#getProjectPath--) should be used instead.

Btw, really cool project!

**Comment by orangy** [comment]
This has been replaced by node support in kotlin/js gradle plugin. Should be working now!
