### ISSUE TITLE
Implement easy publishing to a custom Maven repository

### ISSUE THREAD

**Issue by SvyatoslavScherbina** [Kotlin/kotlinx-benchmark#52]
To adopt kotlinx.benchmark in Kotlin/Native own performance infrastructure, we need to be able to easily publish the library and the plugin to a custom Maven repository (probably somewhere on https://maven.pkg.jetbrains.space) from a branch.

Motivation: we'd like to have a fast feedback loop, because migrating to kotlinx.benchmark would probably require some adjustments to the latter. Same for the further maintenance.

**Comment by qurbonzoda** [comment]
Run of `Deploy(Publish)` build configuration now prompts you to select between "space" and "sonatype" repositories to publish artifacts to. Once space is selected and artifacts are published, they become available in https://maven.pkg.jetbrains.space/kotlin/p/kotlinx/dev repository.
