### ISSUE TITLE
Issue running benchmark with Java 16 

### ISSUE THREAD

**Issue by rptba** [Kotlin/kotlinx-benchmark#63]
Downloaded the repository, runs fine with when the Gradle JVM is set to Java 15 but not Java 16

Working with JDK 15.0.4
Can't compile with JDK 16.0.2

System 
IntelliJ Ultimate 2021.2.1
macOS Big Sur version 11.3.1

`Cause: class org.gradle.internal.compiler.java.ClassNameCollector (in unnamed module @0x7244f195) cannot access class com.sun.tools.javac.code.Symbol$TypeSymbol (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.code to unnamed module @0x7244f195`

**Comment by rinkledink** [comment]
Looks like a similar issue to, upgrading gradle 7 should solve this problem: 
https://github.com/gradle/gradle/issues/16641

But may cause this issue
https://github.com/Kotlin/kotlinx-benchmark/pull/41

**Comment by qurbonzoda** [comment]
Hi,

This issue should be fixed in the latest version of the library: 0.4.10.

Thanks for the feedback. Please don't hesitate to report new issues if you encounter challenges with using the library.
