### ISSUE TITLE
Wrong configuration for 0.2.0-dev-2

### ISSUE THREAD

**Issue by altavir** [Kotlin/kotlinx-benchmark#7]
Dependency configuration requires `0.2.0-dev-2`, not `0.2.0`. Also it requires `maven ("https://dl.bintray.com/orangy/maven")` because of dependency on non-published `kotlinx-cli`.

**Comment by orangy** [comment]
kotlinx-cli dependency will be removed soon, and then we will publish 0.2.0

**Comment by qurbonzoda** [comment]
kotlinx-cli dependency is already removed and library version in README has been fixed, now actual version is `0.2.0-dev-20`.
Thanks for your feedback!
