### ISSUE TITLE
I can't run a single test from Idea gui

### ISSUE THREAD

**Issue by elect86** [Kotlin/kotlinx-benchmark#72]
As titled, if I try to run the following

![Screenshot from 2021-12-16 18-13-57](https://user-images.githubusercontent.com/5020626/146417829-6b1b2931-a2ae-448b-b893-16f078ab982a.png)

it will automatically run this:

` glm:jvmTest:cleanJvmTest glm:jvmTest:jvmTest --tests "glm.func.funcGeometric.test"`

but it'll throw

> Project 'glm' not found in root project 'glm'.

If I modify manually the line into

`cleanJvmTest jvmTest --tests "glm.func.funcGeometric.test"`

Then it's fine again

To reproduce clone this [branch](https://github.com/kotlin-graphics/glm/tree/mp)

**Comment by qurbonzoda** [comment]
Hi,

I am sorry to report that your issue is not related to this project. Therefore, I am closing the issue.
