### ISSUE TITLE
Can't run JS IR benchmarks

### ISSUE THREAD

**Issue by CommanderTvis** [Kotlin/kotlinx-benchmark#80]
Can't run any JS IR benchmark with kotlinx-benchmark 0.4.2

Affected branch: https://github.com/mipt-npm/kmath/tree/commandertvis/js-benchmark

Reproduce:

```
./gradlew benchmarks:jsBenchmark
```
... does not make any effect (no benchmarks are run).

**Comment by olme04** [comment]
Hey @CommanderTvis you have wrong version of `kotlinx-benchmark` plugin configured (specifically 0.3.1). It happens in `buildSrc`: https://github.com/mipt-npm/kmath/blob/commandertvis/js-benchmark/buildSrc/build.gradle.kts#L22
version coming from there overrides plugin version specified in `settings`.
After updating version in `buildSrc` js(IR) benchmarks works.

**Comment by CommanderTvis** [comment]
> Hey @CommanderTvis you have wrong version of `kotlinx-benchmark` plugin configured (specifically 0.3.1). It happens in `buildSrc`: https://github.com/mipt-npm/kmath/blob/commandertvis/js-benchmark/buildSrc/build.gradle.kts#L22 version coming from there overrides plugin version specified in `settings`. After updating version in `buildSrc` js(IR) benchmarks works.

Thank you!
