### ISSUE TITLE
Provide a good implementation of  `Blackhole` for Kotlin/JS

### ISSUE THREAD

**Issue by CommanderTvis** [Kotlin/kotlinx-benchmark#84]
It is really hard to do, but the `Blackhole` concept is really useful…

**Comment by igoriakovlev** [comment]
Implemented with [PR](https://github.com/Kotlin/kotlinx-benchmark/pull/91), implemented in [commit].(https://github.com/Kotlin/kotlinx-benchmark/commit/777fcc9edcf2b1e3e55e1794719276b6837c1ce8).
