### ISSUE TITLE
kotlinx.benchmark 0.4.4 doesn't work with JS IR

### ISSUE THREAD

**Issue by whyoleg** [Kotlin/kotlinx-benchmark#93]
reproducer: https://github.com/rsocket/rsocket-kotlin/tree/kotlinx.benchmark-issue-js (check latest commit, which adds JS IR target)

During IDEA sync fails with `KotlinSourceSet with name 'kotlinBaselineJsIrBenchmark' not found.` JS Legacy syncs successfully

**Comment by whyoleg** [comment]
also reproducible on 0.4.2 with kotlin 1.6.20

**Comment by qurbonzoda** [comment]
This should be fixed in the latest version of the library: 0.4.10.
