### ISSUE TITLE
kotlinx.benchmark 0.4.4 doesn't work with Native

### ISSUE THREAD

**Issue by whyoleg** [Kotlin/kotlinx-benchmark#94]
reproducer: https://github.com/rsocket/rsocket-kotlin/tree/kotlinx.benchmark-issue-native (check latest commit, which adds native support)

Trying to run `kotlinCurrentMacosArm64Benchmark` gradle task fails with `e: Could not find 'main' in 'kotlinx.benchmark.generated' package.`
Generated sources contains `main` method
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/50462752/176023145-6587681c-ff1c-4aa0-8656-6c80167a73af.png">

**Comment by qurbonzoda** [comment]
This should be fixed in the latest version of the library: 0.4.10.
