### ISSUE TITLE
Add support for zip64 or shadowJar option

### ISSUE THREAD

**Issue by harsh201** [Kotlin/kotlinx-benchmark#95]
For complex project with multiple dependencies, kotlinx-benchmark fails to create JMH executable JAR with following error:
```
Execution failed for task ':benchmark:mainBenchmarkJar'.
> archive contains more than 65535 entries.

```
A quick google search revealed that for shadow or uber JAR generation, using zip64 alleviates this issue.

**Comment by qurbonzoda** [comment]
@ThetaSinner I will be happy to accept the PR.
