### ISSUE TITLE
Gradle plugin is unsupported in Gradle 8.0

### ISSUE THREAD

**Issue by dlam** [Kotlin/kotlinx-benchmark#99]
kotlinx.benchmark gradle plugin configures the project in a way that is no longer supported in Gradle 8.0 milestone 2.

Running:
`./gradlew :benchmark:benchmark --no-configration-cache`

Yields the following error:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':benchmark'.
> Adding a Configuration as a dependency is no longer allowed as of Gradle 8.0.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 849ms
```

[The most basic reproducing sample I could make](https://github.com/Kotlin/kotlinx-benchmark/files/9768970/sample.zip). Change macosX64 -> macosArm64 if you are running on an M1.

**Comment by qurbonzoda** [comment]
Gradle 8.0 should be supported since 0.4.6.
For Kotlin 1.8.20+ please use 0.4.8.
